"""Database creation v1.1

Revision ID: 090d2c955a38
Revises: 708c63367b95
Create Date: 2024-06-10 15:17:17.174363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090d2c955a38'
down_revision: Union[str, None] = '708c63367b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'deals_history', 'deals', ['deal_id'], ['deal_id'])
    op.add_column('orders', sa.Column('commission', sa.Numeric(precision=15, scale=14), nullable=False))
    op.alter_column('orders', 'token_amount',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Numeric(precision=15, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'token_amount',
               existing_type=sa.Numeric(precision=15, scale=10),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=False)
    op.drop_column('orders', 'commission')
    op.drop_constraint(None, 'deals_history', type_='foreignkey')
    # ### end Alembic commands ###
